version: "3"

services: 
  app:
    build: .
    image: flaviogf/finance:latest
    entrypoint: bash -c "pipenv run alembic upgrade head && pipenv run gunicorn manage:app --bind 0.0.0.0:80"
    environment: 
      - MAIL_USERNAME=xpto
      - MAIL_PASSWORD=xpto
    ports: 
      - 8000:80
