version: "3"

services: 
  app:
    build: .
    image: flaviogf/finance:latest
    entrypoint: bash -c "pipenv run alembic upgrade head && pipenv run gunicorn manage:app --bind 0.0.0.0:80"
    environment: 
      - MAIL_USERNAME=flavio.fernandes6@gmail.com
      - MAIL_PASSWORD=3z3G//Ks
    ports: 
      - 8000:80
